name: ✨ Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # 💡 Feature Request
        Thanks for taking the time to suggest a new feature! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: 📝 Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve?
      placeholder: This feature would help with...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💭 Proposed Solution
      description: Describe how you'd like this feature to work
      placeholder: |
        Here's how I think it could work:
        1. Add a new button that...
        2. When clicked, it should...
        3. The result would be...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🔥 Priority Level
      options:
        - 🚨 Critical - Blocking work
        - 🔴 High - Needed soon
        - 🟡 Medium - Nice to have
        - 🟢 Low - Could wait
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: What conditions need to be met for this feature to be considered complete?
      placeholder: |
        - [ ] Should be able to...
        - [ ] Should handle error cases by...
        - [ ] Should be accessible via...
        - [ ] Should perform within X seconds
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: |
        Alternative 1:
        - Pros:
        - Cons:

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Additional Context
      description: Add any other context, screenshots, or mockups about the feature request